name: Tecky-project-3
on:
  push:
    branches:
      - "production"
  workflow_dispatch:

env:
  POSTGRES_DB: teckyproject_testing
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  # testing:
  #   runs-on: ubuntu-latest
  #   container: node:latest
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_DB: ${{env.POSTGRES_DB}}
  #         POSTGRES_USER: ${{env.POSTGRES_USER}}
  #         POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}

  #       ports:
  #         - 5432:5432
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         yarn install 
  #         yarn knex migrate:latest --env testing
  #         yarn test
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    # needs: testing
    steps:
      - name: ssh to pull latest version
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd Tecky-project-3
            git pull
            yarn install
            yarn knex migrate:latest --env production
            yarn knex seed:run
            forever restart -c 'yarn dev' . 
          host: 44.213.200.188
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}